#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

CRATE=$1

. $DIR/source/init

## Assumes that solana validator info is checked out as a sibling of this validator
cd $DIR/../../solana

if [ -z "${INCLUDE_DEPS}" ]; then
  cargo depgraph     \
    --workspace-only \
    --root $CRATE    \
    > $DOT_FILE
else
  cargo depgraph  \
    --root $CRATE \
    --depth 2     \
    > $DOT_FILE
fi

open_dot
