#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

CRATE=$1

. $DIR/source/init

## Assumes that solana validator info is checked out as a sibling of this validator
cd $DIR/../../solana

cargo modules dependencies \
  --package $CRATE         \
  --max-depth 1            \
  --layout twopi           \
  > $DOT_FILE

open_dot
