#!/usr/bin/env bash

TRACE_ARR=(
	"warn,"
	"geyser_plugin=trace,"
	"magicblock=trace,"
  "rpc=trace,"
  "solana_geyser_plugin_manager=trace,"
  "solana_svm=trace,"
  "test_tools=trace,"
)

DEBUG_ARR=(
	"warn,"
	"geyser_plugin=debug,"
	"magicblock=debug,"
  "rpc=debug,"
  "solana_geyser_plugin_manager=debug,"
  "solana_svm=debug,"
  "test_tools=debug,"
)

INFO_ARR=(
	"warn,"
	"geyser_plugin=info,"
	"magicblock=info,"
  "rpc=info,"
  "solana_geyser_plugin_manager=info,"
  "solana_svm=info,"
  "test_tools=info,"
)

LOG_LEVEL='info'
TEST_LOG_LEVEL='info'
if [[ $LOG == "INFO" ]]; then
	IFS=''
	LOG_LEVEL="${INFO_ARR[*]}"
  TEST_LOG_LEVEL=$LOG
elif [[ $LOG == "DEBUG" ]]; then
	IFS=''
	LOG_LEVEL="${DEBUG_ARR[*]}"
  TEST_LOG_LEVEL=$LOG
elif [[ $LOG == "TRACE" ]]; then
	IFS=''
	LOG_LEVEL="${TRACE_ARR[*]}"
  TEST_LOG_LEVEL=$LOG
else
	echo "LOG is not set to DEBUG or TRACE (defaulting to 'info')"
fi

export RUST_LOG=$LOG_LEVEL
export RUST_TEST_LOG=$TEST_LOG_LEVEL
